### ISSUE TITLE
Feature request: Exit 1 when updates are availables

### ISSUE THREAD

**Issue by atchisson** [zehengl/pip-check-updates#116]
Hello there,

A small feature request: it would be nice to exit with a non-0 code when updates are detected.

When integrated into a CI environment, this would allow the step to fail, which would be more noticeable than just a log message.

Perhaps this shouldn't be the default behavior, but rather activated with a flag.

Thanks again for the tool. I'll try to look into both issues in my personal time if you'd like!

**Comment by zehengl** [comment]
@all-contributors please add @atchisson for ideas

**Comment by zehengl** [comment]
Closing for https://github.com/zehengl/pip-check-updates/pull/117
