### ISSUE TITLE
Support for `pyproject.toml`, other than Poetry

### ISSUE THREAD

**Issue by ItachiSan** [zehengl/pip-check-updates#20]
Hi!
I believe that adding dependencies support for other major `pyproject.toml`-based tools should be easy to do and very important.

Namely, the tools supported would be:
* setuptools
* flit

I quickly glanced the code and noticed that there is some custom code snooping inside `tool.poetry`, while the relevant information for the above tools are inside `project`.

I am trying to hack up a local version, but I need to know the following:
1. Can / should I use the requirements from:
    https://packaging.pypa.io/en/latest/requirements.html
    or should I reuse some internal code?
2. Is there any requirement for tests / guidelines / others?

Let me know! :wink:

**Comment by zehengl** [comment]
Yes, this is a great idea. PR is welcome!

1. I am open to use `packaging`. Feel free to create a PR that replaces the custom codes 😄 
2. Test as much as you can. Or a minimal to keep the existing tests pass 🤣

**Comment by zehengl** [comment]
@all-contributors please add @ItachiSan for ideas

**Comment by ItachiSan** [comment]
Hi @zehengl ,
I hope to have some time soon to work on this 😄 
Life and work have been quite busy, but I should be able to make a PR soon.

Given your "blessing", I will see if `packaging` helps (it did in my local hack) 😄

**Comment by ItachiSan** [comment]
Another question:
Do you prefer to have multiple small PRs or a huge one?

For example, I refactored the methods in `__init__` to be in their own module.
Should I make a small PR for that?

**Comment by zehengl** [comment]
Yes, please, smaller PR is easier to review.

**Comment by ItachiSan** [comment]
Well, it took some time, but I got some time to work on it and here we go: #50 :wink:

**Comment by ItachiSan** [comment]
Given that #50 is closed, I believe we can close this ticket. :wink:
