### ISSUE TITLE
Crash on included files

### ISSUE THREAD

**Issue by boxed** [zehengl/pip-check-updates#3]
I have several requirements files and they're included from the main one with the `-rsomeotherfile.txt` syntax. This crashes pcu.

**Comment by zehengl** [comment]
It should recognize the `-r` option. Can you share the main requirements file and the error trace?

**Comment by boxed** [comment]
ah, it does handle `-r foo.txt`, but it crashes on `-rfoo.txt` which is also valid pip syntax.

**Comment by zehengl** [comment]
Oh I see. That's a valid point. Thanks for reporting.

**Comment by zehengl** [comment]
@all-contributors please add @boxed for bug
