### ISSUE TITLE
Add flag to retrieve the latest version, including unstable versions

### ISSUE THREAD

**Issue by oyale** [zehengl/pip-check-updates#67]
Hello. Firstly, thank you for this wonderful project and all the hard work you've put into it!

We observed that the current implementation of the script retrieves the latest stable version of a package in PyPi. However, there may be cases where users would like to update to the latest available version, even if it is not stable, to access new features or improvements that are not yet part of a stable release.

Furthermore, it can even [cause regressions](https://github.com/zehengl/pip-check-updates/pull/69#issuecomment-1511353598) when the version pinned in the requirements is unstable, causing the upgrade to downgrade the version to the latest stable version.

To provide this functionality (and fix the unwanted regressions), I propose adding a new command-line flag, `--include-unstable`, that modifies the behavior of the `get_latest_version` function to return the latest available version, regardless of its stability. By default, this flag will be set to `False`, ensuring that the current behavior of returning only stable versions is maintained when the flag is not used.

These changes allow us to effectively fetch the latest unstable version when the `--include-unstable` flag is passed, while still maintaining the original functionality for fetching the latest stable version when the flag is not passed. Please note that this approach works exclusively for packages hosted on PyPI, as other package sources may require different methods for retrieving unstable versions.

We have prepared a pull request with these changes for your review. If you have any concerns or suggestions, please let us know.

Thank you!

**Comment by zehengl** [comment]
@all-contributors please add @oyale for ideas
